model_name: "mistralai/Mistral-7B-v0.1"
use_lora: true
lora_config:
  r: 8
  lora_alpha: 16
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
  lora_dropout: 0.05
  bias: "none"
generation_params:
  temperature: 0.7
  top_p: 0.9
  max_length: 200
  repetition_penalty: 1.1